name: ${project.artifactId}
version: ${project.version}
author: SystemUpdate <contact@systemupdate.io>
main: ${project.groupId}.${project.artifactId}
depend: [HCFactions, Core, Stats, Base]
commands:
  stats: {}
  chest: {}
